# FORMATTER NOTE: The versions of ufmt, black and usort should be consistent everywhere
# (pre-commit, environment.yml, requirements.txt, pyproject.toml, ...)

repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies: [pydoclint==0.7.3]  
        args: [--select=DOC, --config=pydoclint.toml]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      # Run the linter.
      - id: ruff-check
        types_or: [python, pyi ]
        args: [ --fix, --exit-non-zero-on-fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi ]
  - repo: https://github.com/crate-ci/typos
    rev: v1.36.2
    hooks:
      - id: typos
        args: [--config=typos.toml]
        exclude: ^datasets/|octopus_p312.yml|octopus_autosk_p38.yml|octopus_p310.yml|octopus.yml
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
    - id: pyupgrade
      args: [--py312-plus]