# FORMATTER NOTE: The versions of ufmt, black and usort should be consistent everywhere
# (pre-commit, environment.yml, requirements.txt, pyproject.toml, ...)

repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.0
    hooks:
      - id: nbstripout
        args: ['--extra-keys', 'metadata.kernelspec metadata.language_info']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending
        exclude: tests/resources
      - id: check-case-conflict
      - id: trailing-whitespace
        exclude: tests/resources
      - id: end-of-file-fixer
        exclude: tests/resources
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      # - id: check-yaml
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies: [pydoclint==0.7.3]
        args: [--select=DOC, --config=pydoclint.toml]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.13
    hooks:
      - id: ruff-check
        types_or: [python, pyi]
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        types_or: [python, pyi]
  - repo: https://github.com/crate-ci/typos
    rev: v1.38.1
    hooks:
      - id: typos
        args: [--config=typos.toml]
        exclude: octopus.yml
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: [--py312-plus]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.19.1"
    hooks:
      - id: mypy
        exclude: ^datasets/|examples/|tests/|studies/
        additional_dependencies:
          - types-networkx
          - pandas-stubs
          - attrs
          - ray
          - numpy
          - scikit-learn-stubs
          - optuna
          - pytest
          #- mlxtend
          - scipy-stubs
          - joblib-stubs
          #- shap
          #- xgboost
          #- catboost
          #- lz4
          #- autogluon
          - polars
          - plotly-stubs
          - duckdb
          - altair
          - rapidfuzz
        #- boruta
  - repo: local
    hooks:
    - id: license-checker
      name: License Checker
      description: This Hook checks for compatible licenses in all dependencies
      # the `--requirements-paths` must be the last flag because pre-commit appends the pyproject.toml path at the end
      entry: >
        licensecheck
          --extras dev
          --show-only-failing
          -0
          --ignore-package
              apsw
              loro
              "nvidia-cu*"
              "nvidia-nc*"
              "nvidia-nv*"
              matplotlib-inline
              mypy-extensions
          --requirements-paths
      language: python
      files: pyproject.toml
