site_name: Octopus Documentation

theme:
  name: "material"
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - pymdownx.snippets

plugins:
  - mkdocstrings

nav:
  - Octopus Documentation: index.md
  - User Guide:
      - 'userguide/userguide.md'
      - Classification: 'userguide/classification.md'
      - Regression: 'userguide/regression.md'
      - Time to Event: 'userguide/time_to_event.md'
  - Examples: examples/examples.md
  - FAQ: faq.md
  - Changelog: changelog.md
  - Github: 'https://github.com/emdgroup/octopus/'
  - Known Issues: 'https://github.com/emdgroup/octopus/issues/'
  - API Reference:
      - 'reference/reference.md'
      - octopus.manager: 'reference/manager.md'
      - octopus.metrics: 'reference/metrics.md'
      - octopus.models: 'reference/models.md'
      - octopus.modules: 'reference/modules.md'
      - octopus.scripts: 'reference/scripts.md'
      - octopus.study: 'reference/study.md'
      - octopus.task: 'reference/task.md'
  - Contribute: contributing.md
  - Contributors: contributors.md
  - License: license.md
